In [1]:
import numpy as np

In [2]:
#Creating a sample array
brr = np.arange(0,11)

In [4]:
#Show
brr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
brr[8]

8

In [10]:
brr = np.arange(5,21)

In [11]:
brr[8]

13

In [16]:
brr[1:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
brr[:5]

array([5, 6, 7, 8, 9])

In [18]:
brr[1:5]

array([6, 7, 8, 9])

In [23]:
drr = np.arange(5,26)

In [24]:
drr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [30]:
drr[8:17]

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [39]:
#Code 6
#Reset array, we'll see why i had to reset in a moment
grr = np.arange(0,11)

#show
grr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Important notes on slices
slice_of_grr = grr[0:6]

#show slice
slice_of_grr

array([0, 1, 2, 3, 4, 5])

In [42]:
#Change slice
slice_of_grr[:] = 99

#show slice again
slice_of_grr

array([99, 99, 99, 99, 99, 99])

In [45]:
#To get a copy, need to be explicit
grr_copy = grr.copy()

grr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1] 

array([20, 25, 30])

In [49]:
#Format is arr_2d[row][col] or arr_2d[row,col]

#Getting individual element value
arr_2d[1][0]

20

In [50]:
#2D array slicing 

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
trr = np.full((10,10), 0)

trr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
len(trr)

10

In [19]:
arr_length = len(trr)

In [20]:
#set up array

for i in range(arr_length):
    prr[i] = i
    
prr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [10]:
prr[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [24]:
#Code 1 -->
qrr = np.arange(1,11)
qrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
qrr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = qrr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
qrr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
#Rather than going through the three previous process above we can go straight to the point by using this code
qrr[qrr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Code 2
wrr = np.arange(0,10)

In [33]:
wrr + wrr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
wrr * wrr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
wrr - wrr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
#Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Random Tijani\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
#Also warning, but not an error instead infinity
1/arr

C:\Users\Random Tijani\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [42]:
#calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [44]:
np.max(arr) #same as arr.max()

9

In [45]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [46]:
np.log(arr)

C:\Users\Random Tijani\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Cool